### ISSUE TITLE
easytier

### ISSUE THREAD

**Issue by cisen** [cisen/blog#1226]
https://github.com/EasyTier/EasyTier
https://easytier.cn/guide/network/configurations.html
https://github.com/cisen/easytier.github.io （vuepress）
https://github.com/cisen/EasytierGame
https://github.com/cisen/astral
自建服务器：https://easytier.cn/guide/network/host-public-server.html
- 可以使用 `-w udp://abc.com:222/username`指向自己的服务器，https://www.bilibili.com/video/BV1tTX8YNEg3?spm_id_from=333.788.videopod.sections&vd_source=2bda2a236894c8604c19ed5493d25f2d

### 自建服务器
- 可以在 `easytier-web`目录下面运行 `cargo run`
- 在`easytier-web/frontend1` 目录下面运行 `yarn dev` 即可

### 本地tier管理工具GUI
- 文件在`easytier-gui`

### 无公网IP组网
EasyTier 支持共享公网节点进行组网。目前已部署共享的公网节点 ``tcp://public.easytier.cn:11010``。
使用共享节点时，需要每个入网节点提供相同的 ``--network-name`` 和 ``--network-secret`` 参数，作为网络的唯一标识。
以双节点为例，节点 A 执行：
```sh
sudo easytier-core -i 10.144.144.1 --network-name abc --network-secret abc -p tcp://public.easytier.cn:11010
```
节点 B 执行
```sh
sudo easytier-core --ipv4 10.144.144.2 --network-name abc --network-secret abc -p tcp://public.easytier.cn:11010
```
命令执行成功后，节点 A 即可通过虚拟 IP 10.144.144.2 访问节点 B。

### 配置文件
支持使用 -c 参数指定配置文件路径。
```
easytier-core -c ./config.yaml
```
```yaml
instance_name = "default"
dhcp = true
listeners = [
    "tcp://0.0.0.0:11010",
    "udp://0.0.0.0:11010",
    "wg://0.0.0.0:11011",
    "ws://0.0.0.0:11011/",
    "wss://0.0.0.0:11012/",
]
exit_nodes = []
rpc_portal = "0.0.0.0:0"

[[peer]]
uri = "tcp://public.easytier.top:11010"

[network_identity]
network_name = "default"
network_secret = "default"

[flags]
default_protocol = "udp"
dev_name = ""
enable_encryption = true
enable_ipv6 = true
mtu = 1380
latency_first = false
enable_exit_node = false
no_tun = false
use_smoltcp = false
foreign_network_whitelist = "*"
disable_p2p = false
relay_all_peer_rpc = false
disable_udp_hole_punching = false
```
注意

注意：配置文件的优先级更高，当运行时指定了配置文件，则命令行中除 -c 的其他参数将被忽略，只对配置文件生效。
使用参数运行可以获得对应参数的配置文件。配置文件会打印在命令行中，可以手动复制对应配置保存为toml文件即可。

在不使用参数的情况下直接运行 easytier-core 可以获得最小配置文件。

配置文件生成工具
官网提供了[配置文件生成工具](https://easytier.cn/web/index.html#config_generator)，可以通过访问 配置文件生成工具 来生成配置文件。

### docker-compose
```yaml
services:
  watchtower: # 用于自动更新easytier镜像，若不需要请删除这部分
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_NO_STARTUP_MESSAGE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --cleanup --label-enable
  easytier:
    image: easytier/easytier:latest # 国内用户可以使用 m.daocloud.io/docker.io/easytier/easytier:latest
    hostname: easytier
    container_name: easytier
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # 左边是物理机，右边是容器
      - 11010:11010
      - 11010:11010/udp
    volumes:
      # 左边是物理机路径
      - /etc/easytier:/root
      - /etc/machine-id:/etc/machine-id:ro # 映射宿主机机器码
    # -服务器地址可以用公共的，也可以用自己的
    command: -i <ip> --network-name <用户> --network-secret <密码> -p tcp://<服务器地址>:11010

```
