### ISSUE TITLE
Kubernetes 入门相关

### ISSUE THREAD

**Issue by cisen** [cisen/blog#311]
# docker desktop安装
亲测docker edge 2.0.3，使用master可以https://github.com/AliyunContainerService/k8s-for-docker-desktop

**Comment by cisen** [comment]
# 概念说明
## pod
Pod是kubernetes中你可以创建和部署的最小也是最简的单位。Pod代表着集群中运行的进程。、
**在Kubrenetes集群中Pod有如下两种使用方式：**

- **一个Pod中运行一个容器。**“每个Pod中一个容器”的模式是最常见的用法；在这种使用方式中，你可以把Pod想象成是单个容器的封装，kuberentes管理的是Pod而不是直接管理容器。
- **在一个Pod中同时运行多个容器。**一个Pod中也可以同时封装几个需要紧密耦合互相协作的容器，它们之间共享资源。这些在同一个Pod中的容器可以互相协作成为一个service单位——一个容器共享文件，另一个“sidecar”容器来更新这些文件。Pod将这些容器的存储资源作为一个实体来管理。

**Comment by cisen** [comment]
# kubectl命令

**Comment by cisen** [comment]
# 文章收藏
https://blog.csdn.net/wucong60/article/details/81458409
https://blog.csdn.net/wucong60/article/details/81455495
https://blog.csdn.net/wucong60/article/details/81586272
https://blog.csdn.net/wucong60/article/details/81699196

**Comment by cisen** [comment]
#pod 模板
```yaml
{
    "kind": "Pod",（资源类型）
    "apiVersion": "v1",  （资源版本）
    "metadata": {
        "name": "app-tomcat", （名字，唯一）
        "namespace": "default", (命名空间默认default)
        "labels": {
            "name": "app-tomcat" （label做为标识，可以跟RC，Service关联对应）
        }
    },
    "spec": {
        "containers": [
            {
                "name": "app-tomcat", (自定义镜像名称)
                "image": "tomcat", (要拉取的镜像)
                "command": [   (运行容器时，要运行的命令)
                    "/bin/bash",
                    "/opt/apache-tomcat-7.0.57/bin/catalina.sh",
                    "run"
                ],
                "env": [  （环境变量K,V）
                    {
                        "name": "url_addr",
                        "value": "http://192.168.54.66:8080/paas/jsp/index.jsp"
                    }
                ],
                "resources": { （对容器资源限制）
                    "limits": {
                        "cpu": "1",
                        "memory": "1073741824"
                    },
                    "requests": {
                        "cpu": "100m",
                        "memory": "104857600"
                    }
                },
                "imagePullPolicy": "Always" (获取镜像策略Always,Never,IfNotPresent)
            }
        ],
        "restartPolicy": "Always", (pod重启策略,Always,OnFailure,Never)
        "dnsPolicy": "ClusterFirst",
        "nodeSelector": {  (选择将该pod调度到包含这些label的Node上)
            "group": "node1"
        }
    }
}
```
# ReplicationController RC
```yaml
{
    "kind": "ReplicationController",
    "apiVersion": "v1",
    "metadata": {
        "name": "app-tomcat",
        "namespace": "default",
        "labels": {
            "name": "app-tomcat"
        }
    },
    "spec": {
        "replicas": 2（副本数）,
        "selector": {
            "name": "app-tomcat（选择的pod的label）"
        },
        "template": {
            "metadata": {
                "labels": {
                    "name": "app-tomcat（pod的label）"
                }
            },
            "spec": {
                "containers": [
                    {
                        "name": "kaifa2-group-tomcat",
                        "image": "192.168.54.64:5000/tomcat-248:V1.0",
                        "command": [
                            "/bin/bash",
                            "/opt/apache-tomcat-7.0.57/bin/catalina.sh",
                            "run"
                        ],
                        "env": [
                            {
                                "name": "url_addr",
                                "value": "http://192.168.54.64:8080/paas/jsp/index.jsp"
                            }
                        ],
                        "resources": {
                            "limits": {
                                "cpu": "1",
                                "memory": "1073741824"
                            },
                            "requests": {
                                "cpu": "100m",
                                "memory": "104857600"
                            }
                        },
                        "imagePullPolicy": "Always"
                    }
                ],
                "restartPolicy": "Always",
                "nodeSelector": {
                    "group": "node1"
                }
            }
        }
    }
}
```
# Service
```yaml
{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "tomcat-yefp",
        "namespace": "default",
        "labels": {
            "name": "tomcat-yefp"
        }
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 8080（访问端口）,
                "targetPort": 8080
            }
        ],
        "selector": {
            "name": "app-tomcat（选择的pod的label）"
        },
        "type": "ClusterIP",
        "sessionAffinity": "None"
    }
}
```

# Deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-demo
  template:
    metadata:
      labels:
        app: httpd-demo
    spec:
      containers:
      - name: httpd
        image: httpd
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1"
```
