### ISSUE TITLE
docker-compose 相关

### ISSUE THREAD

**Issue by cisen** [cisen/blog#327]
# 简介
docker-compose 是用来做docker 的多容器控制
docker-compose 是一个用来把 docker 自动化的东西。
有了 docker-compose 你可以把所有繁复的 docker 操作全都一条命令，自动化的完成。
Docker-Compose的工程配置文件默认为docker-compose.yml

# Docker-Compose模板文件
Docker-Compose标准模板文件应该包含version、services、networks 三大部分，最关键的是services和networks两个部分。Compose目前有三个版本分别为Version 1，Version 2，Version 3，Compose区分Version 1和Version 2（Compose 1.6.0+，Docker Engine 1.10.0+）。Version 2支持更多的指令。Version 1将来会被弃用。

```yaml
version: '2'
services:
  web:
    image: dockercloud/hello-world
    ports:
      - 8080
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis
    links:
      - web
    networks:
      - back-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
```
