### ISSUE TITLE
kubernets 安装记录

### ISSUE THREAD

**Issue by cisen** [cisen/blog#407]
# 准备
master: 192.168.202.134
node1: 192.168.202.136
node2: 192.168.202.167

**Comment by cisen** [comment]
# kubectl基本操作
kubectl 主要是对pod、service、replicaset、deployment、statefulset、daemonset、job、cronjob、node资源的增删改查。

## 3.1 安装kubectl命令自动补全
```BASH
# 安装kubectl自动补全命令包
yum install -y  bash-completion

# 添加的当前shell
echo "source <(kubectl completion bash)" >> ~/.bashrc
source ~/.bashrc
```

## 3.2 kubectl run命令
kubectl run启动的是deployment、job等类型资源。

```BASH
# 启动一个测试pod，退出pod自动删除
kubectl run ${RANDOM} --rm -it --image=cirros:0.4 -- /bin/sh
  # CirrOS是一个很小的测试镜像，它经常用于测试OpenStack部署

# 在集群启动一个deployment类型的nginx服务
kubectl run nginx-deploy --image=nginx

# 查看deployment。
kubectl get deployments
  # NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
  # nginx-deploy   1         1         1            1           1m

# 查看pods，并显示在哪个node节点
kubectl get pods -o wide
  # NAME                            READY     STATUS    RESTARTS   AGE       IP           NODE
  # nginx-deploy-59c86578c8-vqdqc   1/1       Running   0          1m        10.244.1.2   node01

# 在集群内部任意一个节点都可访问nginx，暂时外部不可访问
curl 10.244.1.2

# 这个nginx服务ip地址是不确定定的，假如删除了pod，重建了新的pod的Ip地址就变化了，为了使nginx服务ip地址固定，需要创建service资源，分配给deployment类型的nginx一个固定的虚拟ip地址
kubectl expose deployment nginx-deploy --name=nginx-service --port=80 --target-port=80

# 查看service信息，可以查看到固定的ip，删除pod或新建的pod的Ip地址虽然会变化，但service的ip不变，形成固定的访问端点
kubectl get service -o wide
  # NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE       SELECTOR
  # kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP   14h       <none>
  # nginx-service   ClusterIP   10.102.228.39   <none>        80/TCP    2m        run=nginx-deploy

# 在集群内任意一个节点访问nginx服务，此时集群外仍然不可访问
curl 10.102.228.39

# 在客户端上通过service名称直接访问，不需要知道service的ip地址。启动一个测试pod：
kubectl run ${RANDOM} --rm -it --image=cirros:0.4 -- /bin/sh

# 在容器里可以直接使用名称直接访问，即便删除service再重建，service的ip改变了，也不影响域名解析。
curl nginx-service

# 集群是怎样能通过名称直接访问的呢？
# 查看集群系统级别的service，有个域名解析服务，ip地址为10.96.0.10
kubectl get service -n kube-system
  # NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
  # kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   14h

# 在容器里查看域名解析
cat /etc/resolv.conf
  # nameserver 10.96.0.10
  # search default.svc.cluster.local svc.cluster.local cluster.local
  # options ndots:5
  # 有了10.96.0.10和search后缀内容，在访问的域名不完整的时候，会把不完整的域名和后缀(/etc/resolv.conf文件search内容)拼接成为完整域名，通过完整的域名，可以解析service名称对应的ip地址了。

# 解析完整的域名
nslookup nginx-service.default.svc.cluster.local


# 通过service详情可以看出关联哪些pods
kubectl describe service nginx-service
  # Name:              nginx-service
  # Namespace:         default
  # Labels:            run=nginx-deploy
  # Annotations:       <none>
  # Selector:          run=nginx-deploy
  # Type:              ClusterIP
  # IP:                10.102.228.39
  # Port:              <unset>  80/TCP
  # TargetPort:        80/TCP
  # Endpoints:         10.244.1.3:80
  # Session Affinity:  None
  # Events:            <none>
  # 其中Labels和Selector标签选择器字段，在pods也有，就是通过selector关联和管理

# 查看pod标签
kubectl get pods --show-labels
  # NAME                            READY     STATUS    RESTARTS   AGE       LABELS
  # nginx-deploy-59c86578c8-2h8w7   1/1       Running   0          12m       pod-template-hash=1574213474,run=nginx-deploy

# 删除原来service
kubectl delete service nginx-service

# 创建集群外可以访问nginx服务的service
kubectl expose deployment nginx-deploy --name=nginx-service --port=80 --target-port=80

# 查看端口映射
kubectl get service

# 在集群外访问nginx服务
curl masster:30193
curl node01:30193
curl node02:30193
```

## 3.3 动态缩放pod的数量和动态更新版本
```BASH
# 启动一个测试pod
kubectl run myapp --image=ikubernetes/myapp:v1 --replicas=3

# 监控查看deployment类型的myapp是否创建完成
kubectl get deployments -w

# 查看pod
kubectl get pods -o wide
  # NAME                            READY     STATUS    RESTARTS   AGE       IP           NODE
  # myapp-848b5b879b-5v5fz          1/1       Running   0          1m        10.244.2.4   node02
  # myapp-848b5b879b-8prhr          1/1       Running   0          1m        10.244.1.4   node01
  # myapp-848b5b879b-vhkcd          1/1       Running   0          1m        10.244.2.3   node02

# 创建service
kubectl expose deployment myapp --name=myapp --port=80 --target-port=80

# 查看service
kubectl get service | grep myapp

# 启动一个交互式busybody来测试
kubectl run bb01 --image=busybox -it

# 在交互式终端是输入下面命令，获取pod名称
while true; do wget -O - -q http://myapp/hostname.html; sleep 1; done;
  # 从结果上看出，获取pod的名称是随机的，说明集群本身带有负载均衡。

# 动态扩展或缩小pod的数量
kubectl scale deployment myapp --replicas=5


# 动态更新版本
  # 在busybody容器执行命令打印当前版本信息
  while true; do wget -O - -q http://myapp; sleep 1; done;

  # 更新镜像
  kubectl set image deployment myapp myapp=ikubernetes/myapp:v2

  # 查看更新过程
  kubectl rollout status deployment myapp

  # 查看pod，发现myapp的pod名称已经全部修改了
  kubectl get pods

  # 在busybody容器可以动态看到版本更新，也可以从deployment中查看当前镜像版本
  kubectl get deployments -o wide


# 回滚旧版本
  # 如果发现新版本有问题，可以回滚到上一个版本
  kubectl rollout undo deployment myapp

  # 查看回滚过程
  kubectl rollout status deployment myapp

  # 在busybody容器打印内容中可以动态看到版本回滚
```

**Comment by cisen** [comment]
# etcd-master默认配置
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://192.168.202.142:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://192.168.202.142:2380
    - --initial-cluster=master=https://192.168.202.142:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://192.168.202.142:2379
    - --listen-peer-urls=https://192.168.202.142:2380
    - --name=master
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd:3.3.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
```

# kube-apiserver
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.202.142
    - --allow-privileged=true
    - --authorization-mode=Node,RBAC
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    image: k8s.gcr.io/kube-apiserver:v1.14.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 192.168.202.142
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
status: {}

````

# kube-controller-manager
```yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-controller-manager
    - --allocate-node-cidrs=true
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf
    - --bind-address=127.0.0.1
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --cluster-cidr=192.168.0.0/16
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --controllers=*,bootstrapsigner,tokencleaner
    - --kubeconfig=/etc/kubernetes/controller-manager.conf
    - --leader-elect=true
    - --node-cidr-mask-size=24
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true
    image: k8s.gcr.io/kube-controller-manager:v1.14.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-controller-manager
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
    - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      name: flexvolume-dir
    - mountPath: /etc/kubernetes/pki
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/kubernetes/controller-manager.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/ssl/certs
      type: DirectoryOrCreate
    name: ca-certs
  - hostPath:
      path: /etc/pki
      type: DirectoryOrCreate
    name: etc-pki
  - hostPath:
      path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
      type: DirectoryOrCreate
    name: flexvolume-dir
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /etc/kubernetes/controller-manager.conf
      type: FileOrCreate
    name: kubeconfig
status: {}

```

# kube-scheduler.yaml 
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: k8s.gcr.io/kube-scheduler:v1.14.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status: {}
```
